import type { UserProfile, Candidate } from "./cupid-store";

// Base API URL for backend (FastAPI / Node.js)
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8000/api";

export interface ChatResponse {
  reply: string;
  suggestedTopics?: string[];
  safetyApproved: boolean;
}

export interface DatePlanItem {
  step: number;
  time: string;
  title: string;
  location: string;
  description: string;
  tag: string;
}

export interface DatePlanResponse {
  candidateName: string;
  theme: string;
  items: DatePlanItem[];
  icebreakerQuestions: string[];
}

export const api = {
  /**
   * Submit user profile & onboarding answers to Profile Agent
   */
  async submitProfile(profile: UserProfile): Promise<{ success: boolean; profileId?: string }> {
    try {
      const res = await fetch(`${API_BASE_URL}/profile`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(profile),
      });
      if (!res.ok) throw new Error(`HTTP error ${res.status}`);
      return await res.json();
    } catch (err) {
      console.warn("[API Client] Backend unavailable, fallback to local store:", err);
      return { success: true };
    }
  },

  /**
   * Fetch matching candidates generated by Matching Agent & Graph
   */
  async getMatches(userEmail: string): Promise<Candidate[]> {
    try {
      const res = await fetch(`${API_BASE_URL}/matches?email=${encodeURIComponent(userEmail)}`);
      if (!res.ok) throw new Error(`HTTP error ${res.status}`);
      return await res.json();
    } catch (err) {
      console.warn("[API Client] Backend unavailable, returning mock matches:", err);
      return [];
    }
  },

  /**
   * Generate customized dating plan via Date Planning Agent
   */
  async generateDatePlan(candidateId: string, customPrompt?: string): Promise<DatePlanResponse> {
    try {
      const res = await fetch(`${API_BASE_URL}/date-plan`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ candidateId, customPrompt }),
      });
      if (!res.ok) throw new Error(`HTTP error ${res.status}`);
      return await res.json();
    } catch (err) {
      console.warn("[API Client] Backend unavailable, returning fallback Date Plan:", err);
      return {
        candidateName: "Đối phương",
        theme: "Buổi hẹn hò lãng mạn & gắn kết tính cách",
        items: [
          {
            step: 1,
            time: "17:30 - 18:45",
            title: "Khởi động & Cà phê kết nối",
            location: "Quán cà phê phong cách Indie ấm cúng",
            description: "Gặp mặt nhẹ nhàng, trò chuyện về sở thích chung và nhịp sống.",
            tag: "Phá băng",
          },
          {
            step: 2,
            time: "19:00 - 20:30",
            title: "Bữa tối lãng mạn & Trò chuyện sâu",
            location: "Nhà hàng không gian yên tĩnh",
            description: "Thưởng thức món ăn yêu thích và chia sẻ các quan niệm sống.",
            tag: "Gắn kết",
          },
          {
            step: 3,
            time: "20:45 - 21:30",
            title: "Dạo phố & Ngắm không gian đêm",
            location: "Phố đi bộ / Công viên bờ sông",
            description: "Dạo bước thư giãn, cùng tạo những kỷ niệm đẹp đầu tiên.",
            tag: "Kỷ niệm",
          },
        ],
        icebreakerQuestions: [
          "Điều gì ở công việc của bạn khiến bạn cảm thấy hào hứng nhất?",
          "Chuyến đi du lịch nào để lại cho bạn ấn tượng sâu sắc nhất?",
          "Nếu có một ngày hoàn toàn tự do, bạn sẽ dành nó để làm gì?",
        ],
      };
    }
  },

  /**
   * Send a chat message to Safety Critic & Response Agent
   */
  async sendMessage(candidateId: string, message: string): Promise<ChatResponse> {
    try {
      const res = await fetch(`${API_BASE_URL}/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ candidateId, message }),
      });
      if (!res.ok) throw new Error(`HTTP error ${res.status}`);
      return await res.json();
    } catch (err) {
      console.warn("[API Client] Backend unavailable, returning fallback response:", err);
      return {
        reply: "Cảm ơn bạn! Hệ thống AI đang được khởi động.",
        safetyApproved: true,
      };
    }
  },
};
